# uncomment below to profile zsh
zmodload zsh/zprof
# make homebrew apps available in path
if [[ $MACHINE == "Darwin" ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

path+=($HOME/.local/bin/)
# Set the directory for storing zinit and plugins
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

# Download zinit, if it's not there.
if [ ! -d "$ZINIT_HOME" ]; then
  mkdir -p "$(dirname $ZINIT_HOME)"
  git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

# Source/Load zinit
source "${ZINIT_HOME}/zinit.zsh"

# Add in oh-my-posh prompt as long as it's not apple's built-in terminal
if [ "$TERM_PROGRAM" != "Apple_Terminal" ]; then
  eval "$(oh-my-posh init zsh --config $HOME/.config/ohmyposh/zen.toml)"
fi

# Add in zsh plugins 
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light Aloxaf/fzf-tab

# Add in Other plugins 
zinit snippet OMZP::git
zinit snippet OMZP::universalarchive
zinit snippet OMZP::extract
zinit snippet OMZP::command-not-found
zinit snippet OMZP::golang

# Load completions when zsh starts
autoload -U compinit && compinit

# replay all of the cached completions 
zinit cdreplay -q

# Keybindings
# set to emacs style
bindkey -e
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward

# Setup History
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# completion styling
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
# create an export for the completion colors
export LS_COLORS="di=34:ln=93;40:so=35;40:pi=33;40:ex=32:bd=1;33;40:cd=1;33;40:su=0;41:sg=0;43:tw=0;42:ow=34;40:"
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' menu no 
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'

# shell integrations
if [[ $MACHINE == "Darwin" ]]; then
  source <(fzf --zsh)
else 
  eval "$(fzf --zsh)"
fi

if [[ $MACHINE == "Darwin" ]]; then
  alias git_protonmail='ssh-add -D && ssh-add ~/.ssh/ed25519_gh_pm_key'
  alias git_gmail='ssh-add -D && ssh-add ~/.ssh/github_gmail_key'
fi

eval "$(zoxide init --cmd cd zsh )"

eval "$(oh-my-posh init zsh --config /Users/scott/.config/oh-my-posh/config.json)"

